spring:
  application:
    name: inventoryservice

logging:
  structured:
    format:
      console: ecs

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8082
