apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice-blue
  labels:
    app: orderservice
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orderservice
      version: blue
  template:
    metadata:
      labels:
        app: orderservice
        version: blue
    spec:
      containers:
        - name: orderservice
          image: udabank/orderservice:blue
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: orderservice-config
            - secretRef:
                name: orderservice-db-credentials
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
